// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package sqlcgen

import (
	"context"
)

const existsConfirmedSeat = `-- name: ExistsConfirmedSeat :one
SELECT EXISTS (
    SELECT 1 FROM confirmed_bookings
    WHERE screening_id = $1
      AND seat_row = $2
      AND seat_number = $3
      AND status = 'confirmed'
)
`

type ExistsConfirmedSeatParams struct {
	ScreeningID string
	SeatRow     string
	SeatNumber  int32
}

// Pre-hold validation (CLAUDE.md §4 "rejected before touching Redis") and
// the phantom-hold defense (ADR 0006): one indexed lookup.
func (q *Queries) ExistsConfirmedSeat(ctx context.Context, arg ExistsConfirmedSeatParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsConfirmedSeat, arg.ScreeningID, arg.SeatRow, arg.SeatNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBookingBySession = `-- name: GetBookingBySession :one
SELECT id, session_id, screening_id, seat_row, seat_number, user_id, status, confirmed_at, updated_at FROM confirmed_bookings WHERE session_id = $1
`

func (q *Queries) GetBookingBySession(ctx context.Context, sessionID string) (ConfirmedBooking, error) {
	row := q.db.QueryRow(ctx, getBookingBySession, sessionID)
	var i ConfirmedBooking
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ScreeningID,
		&i.SeatRow,
		&i.SeatNumber,
		&i.UserID,
		&i.Status,
		&i.ConfirmedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConfirmedBooking = `-- name: InsertConfirmedBooking :one

INSERT INTO confirmed_bookings (session_id, screening_id, seat_row, seat_number, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, screening_id, seat_row, seat_number, user_id, status, confirmed_at, updated_at
`

type InsertConfirmedBookingParams struct {
	SessionID   string
	ScreeningID string
	SeatRow     string
	SeatNumber  int32
	UserID      string
}

// Booking queries. M2 introduced the minimum needed to prove the schema
// constraints; M4 adds the confirm flow's full conflict handling plus the
// seat-map reads.
// Plain insert: the partial unique index on (screening, seat) WHERE
// status='confirmed' is the arbiter — a second confirmed booking for the
// same seat fails with a uniqueness violation (ADR 0006).
func (q *Queries) InsertConfirmedBooking(ctx context.Context, arg InsertConfirmedBookingParams) (ConfirmedBooking, error) {
	row := q.db.QueryRow(ctx, insertConfirmedBooking,
		arg.SessionID,
		arg.ScreeningID,
		arg.SeatRow,
		arg.SeatNumber,
		arg.UserID,
	)
	var i ConfirmedBooking
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ScreeningID,
		&i.SeatRow,
		&i.SeatNumber,
		&i.UserID,
		&i.Status,
		&i.ConfirmedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfirmedSeatsByScreening = `-- name: ListConfirmedSeatsByScreening :many
SELECT seat_row, seat_number
FROM confirmed_bookings
WHERE screening_id = $1
  AND status = 'confirmed'
ORDER BY seat_row, seat_number
`

type ListConfirmedSeatsByScreeningRow struct {
	SeatRow    string
	SeatNumber int32
}

// The seat map's authoritative "booked" layer (ADR 0006: availability is
// computed Postgres-first). Served by the confirmed_bookings_screening_idx
// plus the partial seat index, so it stays an index scan as the table grows.
func (q *Queries) ListConfirmedSeatsByScreening(ctx context.Context, screeningID string) ([]ListConfirmedSeatsByScreeningRow, error) {
	rows, err := q.db.Query(ctx, listConfirmedSeatsByScreening, screeningID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConfirmedSeatsByScreeningRow
	for rows.Next() {
		var i ListConfirmedSeatsByScreeningRow
		if err := rows.Scan(&i.SeatRow, &i.SeatNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookingStatus = `-- name: SetBookingStatus :one
UPDATE confirmed_bookings
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, session_id, screening_id, seat_row, seat_number, user_id, status, confirmed_at, updated_at
`

type SetBookingStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) SetBookingStatus(ctx context.Context, arg SetBookingStatusParams) (ConfirmedBooking, error) {
	row := q.db.QueryRow(ctx, setBookingStatus, arg.ID, arg.Status)
	var i ConfirmedBooking
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ScreeningID,
		&i.SeatRow,
		&i.SeatNumber,
		&i.UserID,
		&i.Status,
		&i.ConfirmedAt,
		&i.UpdatedAt,
	)
	return i, err
}
