// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64
	ActorUserID pgtype.UUID
	Action      string
	EntityType  string
	EntityID    string
	Details     []byte
	CreatedAt   pgtype.Timestamptz
}

type ConfirmedBooking struct {
	ID          string
	SessionID   string
	ScreeningID string
	SeatRow     string
	SeatNumber  int32
	UserID      string
	Status      string
	ConfirmedAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Movie struct {
	ID              string
	Title           string
	Synopsis        string
	DurationMinutes int32
	CreatedAt       pgtype.Timestamptz
}

type Outbox struct {
	ID          int64
	EventID     string
	EventType   string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
}

type Payment struct {
	ID               string
	BookingSessionID string
	Gateway          string
	IntentID         string
	Status           string
	AmountCents      int32
	Currency         string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type RefreshToken struct {
	ID         string
	UserID     string
	FamilyID   string
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	ReplacedBy pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type Screening struct {
	ID          string
	MovieID     string
	StartsAt    pgtype.Timestamptz
	Rows        []string
	SeatsPerRow int32
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	DisplayName  string
	Role         string
	CreatedAt    pgtype.Timestamptz
}
