// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package sqlcgen

import (
	"context"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (title, synopsis, duration_minutes)
VALUES ($1, $2, $3)
RETURNING id, title, synopsis, duration_minutes, created_at
`

type CreateMovieParams struct {
	Title           string
	Synopsis        string
	DurationMinutes int32
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie, arg.Title, arg.Synopsis, arg.DurationMinutes)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Synopsis,
		&i.DurationMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, synopsis, duration_minutes, created_at FROM movies WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id string) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Synopsis,
		&i.DurationMinutes,
		&i.CreatedAt,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, synopsis, duration_minutes, created_at FROM movies ORDER BY title
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Synopsis,
			&i.DurationMinutes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
