// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec

INSERT INTO outbox (event_id, event_type, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxEventParams struct {
	EventID   string
	EventType string
	Payload   []byte
}

// Outbox queries (migrations/00004). The outbox is the transactional
// bridge between "booking committed" and "event published": the
// BookingConfirmed event is written in the SAME Postgres transaction as the
// booking row (ADR 0003's commit point), and the relay in cmd/worker
// publishes it to the broker afterwards (M6). Until then, rows simply
// accumulate with published_at NULL — that buffering IS the point.
// Written atomically with the booking row; the caller supplies event_id,
// event_type, and the JSON payload.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.EventID, arg.EventType, arg.Payload)
	return err
}
