// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlcgen

import (
	"context"
)

const capturePayment = `-- name: CapturePayment :one
UPDATE payments
SET status = 'captured', updated_at = now()
WHERE intent_id = $1 AND status IN ('intent', 'authorized')
RETURNING id, booking_session_id, gateway, intent_id, status, amount_cents, currency, created_at, updated_at
`

// The guarded capture: flips intent/authorized → captured and returns the
// row, or returns ZERO rows if the payment is missing or already terminal.
// The WHERE clause IS the state machine edge (domain/payment
// CanTransitionTo) expressed as SQL, which makes a duplicate webhook
// physically incapable of double-applying: the losing UPDATE blocks on the
// row lock, re-evaluates the predicate, matches nothing. Zero rows is not
// an error by itself — the repo then SELECTs by intent to distinguish
// not-found / already-captured (idempotent no-op) / invalid transition.
func (q *Queries) CapturePayment(ctx context.Context, intentID string) (Payment, error) {
	row := q.db.QueryRow(ctx, capturePayment, intentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingSessionID,
		&i.Gateway,
		&i.IntentID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsCapturedPaymentForSession = `-- name: ExistsCapturedPaymentForSession :one
SELECT EXISTS (
    SELECT 1 FROM payments
    WHERE booking_session_id = $1 AND status = 'captured'
)
`

// The booking confirm gate (application/booking.PaymentFinder): has the
// money for this session moved? First-captured-wins — with at most one
// active intent per session (00009) there is no ordering ambiguity, and
// EXISTS short-circuits on the payments_session_idx index.
func (q *Queries) ExistsCapturedPaymentForSession(ctx context.Context, bookingSessionID string) (bool, error) {
	row := q.db.QueryRow(ctx, existsCapturedPaymentForSession, bookingSessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const failPayment = `-- name: FailPayment :one
UPDATE payments
SET status = 'failed', updated_at = now()
WHERE intent_id = $1 AND status IN ('intent', 'authorized')
RETURNING id, booking_session_id, gateway, intent_id, status, amount_cents, currency, created_at, updated_at
`

// Same guard shape as CapturePayment for the intent/authorized → failed
// edge: gateway declines and webhook amount mismatches land here. A
// captured row can NEVER become failed (money that moved exits only via
// refund), and the guard makes that true at the DB level, not just in the
// domain table. Zero rows → the repo SELECTs to classify, same as capture.
func (q *Queries) FailPayment(ctx context.Context, intentID string) (Payment, error) {
	row := q.db.QueryRow(ctx, failPayment, intentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingSessionID,
		&i.Gateway,
		&i.IntentID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePaymentBySession = `-- name: GetActivePaymentBySession :one
SELECT id, booking_session_id, gateway, intent_id, status, amount_cents, currency, created_at, updated_at FROM payments
WHERE booking_session_id = $1
  AND status NOT IN ('failed', 'refunded')
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The session's live intent: latest non-terminal row. The status predicate
// mirrors payments_active_session_unique EXACTLY (migration 00009) so the
// read and the arbiter can never disagree about what "active" means. The id
// tiebreak exists because created_at is now()-stamped and two rows inserted
// in one transaction instant would otherwise tie.
func (q *Queries) GetActivePaymentBySession(ctx context.Context, bookingSessionID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getActivePaymentBySession, bookingSessionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingSessionID,
		&i.Gateway,
		&i.IntentID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIntent = `-- name: GetPaymentByIntent :one
SELECT id, booking_session_id, gateway, intent_id, status, amount_cents, currency, created_at, updated_at FROM payments WHERE intent_id = $1
`

// Intent lookup by the gateway's ID (payments_intent_unique). This is the
// webhook's entry point: the provider names an intent, we find our row.
func (q *Queries) GetPaymentByIntent(ctx context.Context, intentID string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIntent, intentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingSessionID,
		&i.Gateway,
		&i.IntentID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaymentIntent = `-- name: InsertPaymentIntent :one

INSERT INTO payments (booking_session_id, gateway, intent_id, status, amount_cents, currency)
VALUES ($1, $2, $3, 'intent', $4, $5)
RETURNING id, booking_session_id, gateway, intent_id, status, amount_cents, currency, created_at, updated_at
`

type InsertPaymentIntentParams struct {
	BookingSessionID string
	Gateway          string
	IntentID         string
	AmountCents      int32
	Currency         string
}

// Payments queries (M5, CLAUDE.md §7, ADR 0008). The concurrency design in
// one sentence: the SCHEMA is the arbiter — inserts collide on
// payments_active_session_unique, captures are guarded conditional UPDATEs,
// and the confirm gate is an EXISTS. No read-modify-write anywhere.
// Records a freshly gateway-minted intent. 23505 on
// payments_active_session_unique means a concurrent CreateIntent won the
// race; the repo maps that to ErrPaymentIntentExists and the service
// recovers by returning the winner (same shape as booking confirm's
// idempotent recovery, ADR 0006). 23505 on payments_intent_unique would be
// a gateway ID collision — impossible by construction (UUIDs); the repo
// logs it loudly rather than guessing.
func (q *Queries) InsertPaymentIntent(ctx context.Context, arg InsertPaymentIntentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPaymentIntent,
		arg.BookingSessionID,
		arg.Gateway,
		arg.IntentID,
		arg.AmountCents,
		arg.Currency,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingSessionID,
		&i.Gateway,
		&i.IntentID,
		&i.Status,
		&i.AmountCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
