// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (id, user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, created_at
`

type CreateRefreshTokenParams struct {
	ID        string
	UserID    string
	FamilyID  string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

// Refresh-token queries (ADR 0004). The rotation state machine itself is
// documented on auth.RefreshTokenStore.Rotate; these are the SQL building
// blocks it composes inside a transaction.
// The row ID is minted by the application (uuid v4), not by the database:
// both store implementations must agree on who assigns identity, and the
// in-memory fake has no gen_random_uuid().
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by, created_at FROM refresh_tokens WHERE token_hash = $1 FOR UPDATE
`

// Row lock for Rotate's critical section. MUST run inside a transaction:
// outside one the FOR UPDATE lock evaporates with the statement and the
// read-decide-write is no longer atomic.
func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const markRefreshTokenReplaced = `-- name: MarkRefreshTokenReplaced :exec
UPDATE refresh_tokens SET replaced_by = $2 WHERE id = $1
`

type MarkRefreshTokenReplacedParams struct {
	ID         string
	ReplacedBy pgtype.UUID
}

func (q *Queries) MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenReplaced, arg.ID, arg.ReplacedBy)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

// Theft detection and logout both flow through here. Idempotent: rows
// already revoked keep their original revoked_at.
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}
