// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: screenings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScreening = `-- name: CreateScreening :one
INSERT INTO screenings (movie_id, starts_at, rows, seats_per_row)
VALUES ($1, $2, $3, $4)
RETURNING id, movie_id, starts_at, rows, seats_per_row, created_at
`

type CreateScreeningParams struct {
	MovieID     string
	StartsAt    pgtype.Timestamptz
	Rows        []string
	SeatsPerRow int32
}

func (q *Queries) CreateScreening(ctx context.Context, arg CreateScreeningParams) (Screening, error) {
	row := q.db.QueryRow(ctx, createScreening,
		arg.MovieID,
		arg.StartsAt,
		arg.Rows,
		arg.SeatsPerRow,
	)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.StartsAt,
		&i.Rows,
		&i.SeatsPerRow,
		&i.CreatedAt,
	)
	return i, err
}

const getScreening = `-- name: GetScreening :one
SELECT id, movie_id, starts_at, rows, seats_per_row, created_at FROM screenings WHERE id = $1
`

func (q *Queries) GetScreening(ctx context.Context, id string) (Screening, error) {
	row := q.db.QueryRow(ctx, getScreening, id)
	var i Screening
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.StartsAt,
		&i.Rows,
		&i.SeatsPerRow,
		&i.CreatedAt,
	)
	return i, err
}

const listScreeningsByMovie = `-- name: ListScreeningsByMovie :many
SELECT id, movie_id, starts_at, rows, seats_per_row, created_at FROM screenings
WHERE movie_id = $1
ORDER BY starts_at
`

func (q *Queries) ListScreeningsByMovie(ctx context.Context, movieID string) ([]Screening, error) {
	rows, err := q.db.Query(ctx, listScreeningsByMovie, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Screening
	for rows.Next() {
		var i Screening
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.StartsAt,
			&i.Rows,
			&i.SeatsPerRow,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
